services:
  - type: web
    name: plataforma-penafiel
    runtime: python
    plan: free
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --workers 1 --threads 2 --timeout 120
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: DEBUG
        value: False
      - key: SECRET_KEY
        generateValue: true
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_HOST
        sync: false
      - key: DB_NAME
        value: penafiel
      - key: DATA_DIR
        value: /opt/render/project/src/data
      - key: GRAFICAS_DIR
        value: /opt/render/project/src/graficas
      - key: CODIGOS_DIR
        value: /opt/render/project/src/modules
